### ISSUE TITLE
MESSAGE_WRITE problem

### ISSUE THREAD

**Issue by Apelsin4k** [M5rian/JdaCommandHandler#3]
Hello, When I launch the bot I get an error 
```
[JDA MainWS-ReadThread] ERROR net.dv8tion.jda.api.JDA - One of the EventListeners had an uncaught exception
java.lang.NoSuchFieldError: MESSAGE_WRITE
```
How i can fix it?

**Comment by m5rian** [comment]
Which JDA version are you using?

**Comment by Apelsin4k** [comment]
I use JDA 5

**Comment by m5rian** [comment]
Yeah the library is for JDA 4 and does not support JDA 5 yet. If you want to use the handler use JDA 4.x. I will port this lib once the stable JDA 5 gets released. Right now it's still in alpha stage.
